// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: inventory.sql

package repository

import (
	"context"
	"database/sql"
	"time"
)

const cleanupExpiredIdempotencyKeys = `-- name: CleanupExpiredIdempotencyKeys :exec
DELETE FROM idempotency_keys
WHERE expires_at < CURRENT_TIMESTAMP
`

// Cleanup expired idempotency keys
func (q *Queries) CleanupExpiredIdempotencyKeys(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, cleanupExpiredIdempotencyKeys)
	return err
}

const convertReservationToSale = `-- name: ConvertReservationToSale :one
UPDATE inventory_items 
SET 
    reserved_stock = reserved_stock - ?,
    version = version + 1,
    updated_at = CURRENT_TIMESTAMP
WHERE 
    product_id = ? 
    AND reserved_stock >= ?
RETURNING id, product_id, available_stock, reserved_stock, version, created_at, updated_at
`

type ConvertReservationToSaleParams struct {
	ReservedStock   int64  `json:"reserved_stock"`
	ProductID       string `json:"product_id"`
	ReservedStock_2 int64  `json:"reserved_stock_2"`
}

// Convert reservation to sale (decrease reserved, don't change available)
func (q *Queries) ConvertReservationToSale(ctx context.Context, arg ConvertReservationToSaleParams) (InventoryItem, error) {
	row := q.db.QueryRowContext(ctx, convertReservationToSale, arg.ReservedStock, arg.ProductID, arg.ReservedStock_2)
	var i InventoryItem
	err := row.Scan(
		&i.ID,
		&i.ProductID,
		&i.AvailableStock,
		&i.ReservedStock,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createIdempotencyKey = `-- name: CreateIdempotencyKey :one
INSERT INTO idempotency_keys (request_id, operation_type, response_data, expires_at)
VALUES (?, ?, ?, ?)
RETURNING request_id, operation_type, response_data, created_at, expires_at
`

type CreateIdempotencyKeyParams struct {
	RequestID     string         `json:"request_id"`
	OperationType string         `json:"operation_type"`
	ResponseData  sql.NullString `json:"response_data"`
	ExpiresAt     time.Time      `json:"expires_at"`
}

// Idempotency queries (adapting to existing schema)
func (q *Queries) CreateIdempotencyKey(ctx context.Context, arg CreateIdempotencyKeyParams) (IdempotencyKey, error) {
	row := q.db.QueryRowContext(ctx, createIdempotencyKey,
		arg.RequestID,
		arg.OperationType,
		arg.ResponseData,
		arg.ExpiresAt,
	)
	var i IdempotencyKey
	err := row.Scan(
		&i.RequestID,
		&i.OperationType,
		&i.ResponseData,
		&i.CreatedAt,
		&i.ExpiresAt,
	)
	return i, err
}

const createInventoryItem = `-- name: CreateInventoryItem :one
INSERT INTO inventory_items (id, product_id, available_stock, reserved_stock)
VALUES (?, ?, ?, 0)
RETURNING id, product_id, available_stock, reserved_stock, version, created_at, updated_at
`

type CreateInventoryItemParams struct {
	ID             string `json:"id"`
	ProductID      string `json:"product_id"`
	AvailableStock int64  `json:"available_stock"`
}

// Inventory Items queries (adapting to existing schema)
func (q *Queries) CreateInventoryItem(ctx context.Context, arg CreateInventoryItemParams) (InventoryItem, error) {
	row := q.db.QueryRowContext(ctx, createInventoryItem, arg.ID, arg.ProductID, arg.AvailableStock)
	var i InventoryItem
	err := row.Scan(
		&i.ID,
		&i.ProductID,
		&i.AvailableStock,
		&i.ReservedStock,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createProduct = `-- name: CreateProduct :one
INSERT INTO products (id, name, description)
VALUES (?, ?, ?)
RETURNING id, name, description, created_at, updated_at
`

type CreateProductParams struct {
	ID          string         `json:"id"`
	Name        string         `json:"name"`
	Description sql.NullString `json:"description"`
}

// Products queries
func (q *Queries) CreateProduct(ctx context.Context, arg CreateProductParams) (Product, error) {
	row := q.db.QueryRowContext(ctx, createProduct, arg.ID, arg.Name, arg.Description)
	var i Product
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createReservation = `-- name: CreateReservation :one
INSERT INTO reservations (id, product_id, quantity, request_id, status, expires_at)
VALUES (?, ?, ?, ?, 'pending', ?)
RETURNING id, request_id, product_id, quantity, status, created_at, updated_at, expires_at
`

type CreateReservationParams struct {
	ID        string       `json:"id"`
	ProductID string       `json:"product_id"`
	Quantity  int64        `json:"quantity"`
	RequestID string       `json:"request_id"`
	ExpiresAt sql.NullTime `json:"expires_at"`
}

// Reservations queries (adapting to existing schema)
func (q *Queries) CreateReservation(ctx context.Context, arg CreateReservationParams) (Reservation, error) {
	row := q.db.QueryRowContext(ctx, createReservation,
		arg.ID,
		arg.ProductID,
		arg.Quantity,
		arg.RequestID,
		arg.ExpiresAt,
	)
	var i Reservation
	err := row.Scan(
		&i.ID,
		&i.RequestID,
		&i.ProductID,
		&i.Quantity,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ExpiresAt,
	)
	return i, err
}

const createReservationWithTimeout = `-- name: CreateReservationWithTimeout :one
INSERT INTO reservations (id, product_id, quantity, request_id, status, expires_at, created_at)
VALUES (?1, ?2, ?3, ?4, 'active', ?5, CURRENT_TIMESTAMP)
RETURNING id, request_id, product_id, quantity, status, created_at, updated_at, expires_at
`

type CreateReservationWithTimeoutParams struct {
	ID        string       `json:"id"`
	ProductID string       `json:"product_id"`
	Quantity  int64        `json:"quantity"`
	RequestID string       `json:"request_id"`
	ExpiresAt sql.NullTime `json:"expires_at"`
}

// Create reservation with timeout and validation
func (q *Queries) CreateReservationWithTimeout(ctx context.Context, arg CreateReservationWithTimeoutParams) (Reservation, error) {
	row := q.db.QueryRowContext(ctx, createReservationWithTimeout,
		arg.ID,
		arg.ProductID,
		arg.Quantity,
		arg.RequestID,
		arg.ExpiresAt,
	)
	var i Reservation
	err := row.Scan(
		&i.ID,
		&i.RequestID,
		&i.ProductID,
		&i.Quantity,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ExpiresAt,
	)
	return i, err
}

const deleteExpiredIdempotencyKeys = `-- name: DeleteExpiredIdempotencyKeys :exec
DELETE FROM idempotency_keys
WHERE expires_at < CURRENT_TIMESTAMP
`

func (q *Queries) DeleteExpiredIdempotencyKeys(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, deleteExpiredIdempotencyKeys)
	return err
}

const getExpiredReservations = `-- name: GetExpiredReservations :many

SELECT id, product_id, quantity, request_id, expires_at, created_at
FROM reservations
WHERE status = 'active' 
AND expires_at < CURRENT_TIMESTAMP
ORDER BY expires_at ASC
LIMIT ?1
`

type GetExpiredReservationsRow struct {
	ID        string       `json:"id"`
	ProductID string       `json:"product_id"`
	Quantity  int64        `json:"quantity"`
	RequestID string       `json:"request_id"`
	ExpiresAt sql.NullTime `json:"expires_at"`
	CreatedAt time.Time    `json:"created_at"`
}

// Update reservation status with optimistic approach\n-- name: UpdateReservationStatus :one\nUPDATE reservations\nSET \n    status = ?1,\n    updated_at = CURRENT_TIMESTAMP\nWHERE id = ?2 AND status = 'active'  -- Only update active reservations\nRETURNING *;
// Get active reservations for cleanup
func (q *Queries) GetExpiredReservations(ctx context.Context, limit int64) ([]GetExpiredReservationsRow, error) {
	rows, err := q.db.QueryContext(ctx, getExpiredReservations, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetExpiredReservationsRow{}
	for rows.Next() {
		var i GetExpiredReservationsRow
		if err := rows.Scan(
			&i.ID,
			&i.ProductID,
			&i.Quantity,
			&i.RequestID,
			&i.ExpiresAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getIdempotencyKey = `-- name: GetIdempotencyKey :one
SELECT request_id, operation_type, response_data, created_at, expires_at FROM idempotency_keys
WHERE request_id = ? LIMIT 1
`

func (q *Queries) GetIdempotencyKey(ctx context.Context, requestID string) (IdempotencyKey, error) {
	row := q.db.QueryRowContext(ctx, getIdempotencyKey, requestID)
	var i IdempotencyKey
	err := row.Scan(
		&i.RequestID,
		&i.OperationType,
		&i.ResponseData,
		&i.CreatedAt,
		&i.ExpiresAt,
	)
	return i, err
}

const getInventoryForUpdate = `-- name: GetInventoryForUpdate :one
SELECT id, product_id, available_stock, reserved_stock, version, created_at, updated_at
FROM inventory_items
WHERE product_id = ?1
LIMIT 1
`

// Get inventory with version for optimistic locking
func (q *Queries) GetInventoryForUpdate(ctx context.Context, productID string) (InventoryItem, error) {
	row := q.db.QueryRowContext(ctx, getInventoryForUpdate, productID)
	var i InventoryItem
	err := row.Scan(
		&i.ID,
		&i.ProductID,
		&i.AvailableStock,
		&i.ReservedStock,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getInventoryItem = `-- name: GetInventoryItem :one
SELECT id, product_id, available_stock, reserved_stock, version, created_at, updated_at FROM inventory_items
WHERE product_id = ? LIMIT 1
`

func (q *Queries) GetInventoryItem(ctx context.Context, productID string) (InventoryItem, error) {
	row := q.db.QueryRowContext(ctx, getInventoryItem, productID)
	var i InventoryItem
	err := row.Scan(
		&i.ID,
		&i.ProductID,
		&i.AvailableStock,
		&i.ReservedStock,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getInventoryItemWithVersion = `-- name: GetInventoryItemWithVersion :one
SELECT id, product_id, available_stock, reserved_stock, version, created_at, updated_at FROM inventory_items
WHERE product_id = ? AND version = ? LIMIT 1
`

type GetInventoryItemWithVersionParams struct {
	ProductID string `json:"product_id"`
	Version   int64  `json:"version"`
}

func (q *Queries) GetInventoryItemWithVersion(ctx context.Context, arg GetInventoryItemWithVersionParams) (InventoryItem, error) {
	row := q.db.QueryRowContext(ctx, getInventoryItemWithVersion, arg.ProductID, arg.Version)
	var i InventoryItem
	err := row.Scan(
		&i.ID,
		&i.ProductID,
		&i.AvailableStock,
		&i.ReservedStock,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getInventorySummary = `-- name: GetInventorySummary :one
SELECT 
    COUNT(*) as total_products,
    SUM(available_stock + reserved_stock) as total_stock,
    SUM(reserved_stock) as total_reserved,
    SUM(available_stock) as total_available
FROM inventory_items
`

type GetInventorySummaryRow struct {
	TotalProducts  int64           `json:"total_products"`
	TotalStock     sql.NullFloat64 `json:"total_stock"`
	TotalReserved  sql.NullFloat64 `json:"total_reserved"`
	TotalAvailable sql.NullFloat64 `json:"total_available"`
}

// Inventory reporting queries (adapting to existing schema)
func (q *Queries) GetInventorySummary(ctx context.Context) (GetInventorySummaryRow, error) {
	row := q.db.QueryRowContext(ctx, getInventorySummary)
	var i GetInventorySummaryRow
	err := row.Scan(
		&i.TotalProducts,
		&i.TotalStock,
		&i.TotalReserved,
		&i.TotalAvailable,
	)
	return i, err
}

const getLowStockProducts = `-- name: GetLowStockProducts :many
SELECT 
    p.id, p.name,
    i.available_stock, i.reserved_stock, i.available_stock as available
FROM products p
JOIN inventory_items i ON p.id = i.product_id
WHERE i.available_stock <= ?
ORDER BY available ASC
`

type GetLowStockProductsRow struct {
	ID             string `json:"id"`
	Name           string `json:"name"`
	AvailableStock int64  `json:"available_stock"`
	ReservedStock  int64  `json:"reserved_stock"`
	Available      int64  `json:"available"`
}

func (q *Queries) GetLowStockProducts(ctx context.Context, availableStock int64) ([]GetLowStockProductsRow, error) {
	rows, err := q.db.QueryContext(ctx, getLowStockProducts, availableStock)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetLowStockProductsRow{}
	for rows.Next() {
		var i GetLowStockProductsRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.AvailableStock,
			&i.ReservedStock,
			&i.Available,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getProduct = `-- name: GetProduct :one
SELECT id, name, description, created_at, updated_at FROM products
WHERE id = ? LIMIT 1
`

func (q *Queries) GetProduct(ctx context.Context, id string) (Product, error) {
	row := q.db.QueryRowContext(ctx, getProduct, id)
	var i Product
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getReservation = `-- name: GetReservation :one
SELECT id, request_id, product_id, quantity, status, created_at, updated_at, expires_at FROM reservations
WHERE id = ? LIMIT 1
`

func (q *Queries) GetReservation(ctx context.Context, id string) (Reservation, error) {
	row := q.db.QueryRowContext(ctx, getReservation, id)
	var i Reservation
	err := row.Scan(
		&i.ID,
		&i.RequestID,
		&i.ProductID,
		&i.Quantity,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ExpiresAt,
	)
	return i, err
}

const getReservationByRequestID = `-- name: GetReservationByRequestID :one
SELECT id, request_id, product_id, quantity, status, created_at, updated_at, expires_at FROM reservations
WHERE request_id = ? LIMIT 1
`

func (q *Queries) GetReservationByRequestID(ctx context.Context, requestID string) (Reservation, error) {
	row := q.db.QueryRowContext(ctx, getReservationByRequestID, requestID)
	var i Reservation
	err := row.Scan(
		&i.ID,
		&i.RequestID,
		&i.ProductID,
		&i.Quantity,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ExpiresAt,
	)
	return i, err
}

const getReservationsByProduct = `-- name: GetReservationsByProduct :many
SELECT id, request_id, product_id, quantity, status, created_at, updated_at, expires_at FROM reservations
WHERE product_id = ? AND status = 'active'
ORDER BY created_at
`

func (q *Queries) GetReservationsByProduct(ctx context.Context, productID string) ([]Reservation, error) {
	rows, err := q.db.QueryContext(ctx, getReservationsByProduct, productID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Reservation{}
	for rows.Next() {
		var i Reservation
		if err := rows.Scan(
			&i.ID,
			&i.RequestID,
			&i.ProductID,
			&i.Quantity,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ExpiresAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getValidIdempotencyKey = `-- name: GetValidIdempotencyKey :one
SELECT request_id, operation_type, response_data, created_at, expires_at
FROM idempotency_keys
WHERE request_id = ?1 
AND expires_at > CURRENT_TIMESTAMP
LIMIT 1
`

// Get idempotency key if not expired
func (q *Queries) GetValidIdempotencyKey(ctx context.Context, requestID string) (IdempotencyKey, error) {
	row := q.db.QueryRowContext(ctx, getValidIdempotencyKey, requestID)
	var i IdempotencyKey
	err := row.Scan(
		&i.RequestID,
		&i.OperationType,
		&i.ResponseData,
		&i.CreatedAt,
		&i.ExpiresAt,
	)
	return i, err
}

const listActiveReservations = `-- name: ListActiveReservations :many
SELECT id, request_id, product_id, quantity, status, created_at, updated_at, expires_at FROM reservations
WHERE status = 'active'
ORDER BY created_at
`

func (q *Queries) ListActiveReservations(ctx context.Context) ([]Reservation, error) {
	rows, err := q.db.QueryContext(ctx, listActiveReservations)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Reservation{}
	for rows.Next() {
		var i Reservation
		if err := rows.Scan(
			&i.ID,
			&i.RequestID,
			&i.ProductID,
			&i.Quantity,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ExpiresAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listExpiredReservations = `-- name: ListExpiredReservations :many
SELECT id, request_id, product_id, quantity, status, created_at, updated_at, expires_at FROM reservations
WHERE status = 'active' AND expires_at < CURRENT_TIMESTAMP
ORDER BY expires_at
`

func (q *Queries) ListExpiredReservations(ctx context.Context) ([]Reservation, error) {
	rows, err := q.db.QueryContext(ctx, listExpiredReservations)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Reservation{}
	for rows.Next() {
		var i Reservation
		if err := rows.Scan(
			&i.ID,
			&i.RequestID,
			&i.ProductID,
			&i.Quantity,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ExpiresAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProducts = `-- name: ListProducts :many
SELECT id, name, description, created_at, updated_at FROM products
ORDER BY name
`

func (q *Queries) ListProducts(ctx context.Context) ([]Product, error) {
	rows, err := q.db.QueryContext(ctx, listProducts)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Product{}
	for rows.Next() {
		var i Product
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markReservationsExpired = `-- name: MarkReservationsExpired :exec
UPDATE reservations
SET 
    status = 'expired',
    updated_at = CURRENT_TIMESTAMP
WHERE status = 'active' 
AND expires_at < CURRENT_TIMESTAMP
`

// Batch release expired reservations
func (q *Queries) MarkReservationsExpired(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, markReservationsExpired)
	return err
}

const releaseReservedStock = `-- name: ReleaseReservedStock :one
UPDATE inventory_items 
SET 
    available_stock = available_stock + ?,
    reserved_stock = reserved_stock - ?,
    version = version + 1,
    updated_at = CURRENT_TIMESTAMP
WHERE 
    product_id = ? 
    AND reserved_stock >= ?
RETURNING id, product_id, available_stock, reserved_stock, version, created_at, updated_at
`

type ReleaseReservedStockParams struct {
	AvailableStock  int64  `json:"available_stock"`
	ReservedStock   int64  `json:"reserved_stock"`
	ProductID       string `json:"product_id"`
	ReservedStock_2 int64  `json:"reserved_stock_2"`
}

// Release reserved stock (decrease reserved, increase available)
func (q *Queries) ReleaseReservedStock(ctx context.Context, arg ReleaseReservedStockParams) (InventoryItem, error) {
	row := q.db.QueryRowContext(ctx, releaseReservedStock,
		arg.AvailableStock,
		arg.ReservedStock,
		arg.ProductID,
		arg.ReservedStock_2,
	)
	var i InventoryItem
	err := row.Scan(
		&i.ID,
		&i.ProductID,
		&i.AvailableStock,
		&i.ReservedStock,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const releaseStockOptimistic = `-- name: ReleaseStockOptimistic :one
UPDATE inventory_items 
SET 
    available_stock = available_stock + ?1,
    reserved_stock = reserved_stock - ?1,
    version = version + 1,
    updated_at = CURRENT_TIMESTAMP
WHERE 
    product_id = ?2 
    AND version = ?3
    AND reserved_stock >= ?1  -- Ensure sufficient reserved stock
RETURNING id, product_id, available_stock, reserved_stock, version, created_at, updated_at
`

type ReleaseStockOptimisticParams struct {
	AvailableStock int64  `json:"available_stock"`
	ProductID      string `json:"product_id"`
	Version        int64  `json:"version"`
}

// Critical: Optimistic stock release with validation
func (q *Queries) ReleaseStockOptimistic(ctx context.Context, arg ReleaseStockOptimisticParams) (InventoryItem, error) {
	row := q.db.QueryRowContext(ctx, releaseStockOptimistic, arg.AvailableStock, arg.ProductID, arg.Version)
	var i InventoryItem
	err := row.Scan(
		&i.ID,
		&i.ProductID,
		&i.AvailableStock,
		&i.ReservedStock,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const reserveStockOptimistic = `-- name: ReserveStockOptimistic :one

UPDATE inventory_items 
SET 
    available_stock = available_stock - ?1,
    reserved_stock = reserved_stock + ?1,
    version = version + 1,
    updated_at = CURRENT_TIMESTAMP
WHERE 
    product_id = ?2 
    AND version = ?3
    AND (available_stock - ?1) >= 0  -- Prevent negative available stock
    AND (available_stock >= ?1)      -- Ensure sufficient stock
RETURNING id, product_id, available_stock, reserved_stock, version, created_at, updated_at
`

type ReserveStockOptimisticParams struct {
	AvailableStock int64  `json:"available_stock"`
	ProductID      string `json:"product_id"`
	Version        int64  `json:"version"`
}

// =====================================================
// ENHANCED OPTIMISTIC LOCKING QUERIES
// =====================================================
// Critical: Optimistic stock reservation with comprehensive validation
func (q *Queries) ReserveStockOptimistic(ctx context.Context, arg ReserveStockOptimisticParams) (InventoryItem, error) {
	row := q.db.QueryRowContext(ctx, reserveStockOptimistic, arg.AvailableStock, arg.ProductID, arg.Version)
	var i InventoryItem
	err := row.Scan(
		&i.ID,
		&i.ProductID,
		&i.AvailableStock,
		&i.ReservedStock,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const reserveStockWithVersion = `-- name: ReserveStockWithVersion :one
UPDATE inventory_items 
SET 
    available_stock = available_stock - ?,
    reserved_stock = reserved_stock + ?,
    version = version + 1,
    updated_at = CURRENT_TIMESTAMP
WHERE 
    product_id = ? 
    AND version = ?
    AND available_stock >= ?
RETURNING id, product_id, available_stock, reserved_stock, version, created_at, updated_at
`

type ReserveStockWithVersionParams struct {
	AvailableStock   int64  `json:"available_stock"`
	ReservedStock    int64  `json:"reserved_stock"`
	ProductID        string `json:"product_id"`
	Version          int64  `json:"version"`
	AvailableStock_2 int64  `json:"available_stock_2"`
}

// Reserve stock (decrease available, increase reserved)
func (q *Queries) ReserveStockWithVersion(ctx context.Context, arg ReserveStockWithVersionParams) (InventoryItem, error) {
	row := q.db.QueryRowContext(ctx, reserveStockWithVersion,
		arg.AvailableStock,
		arg.ReservedStock,
		arg.ProductID,
		arg.Version,
		arg.AvailableStock_2,
	)
	var i InventoryItem
	err := row.Scan(
		&i.ID,
		&i.ProductID,
		&i.AvailableStock,
		&i.ReservedStock,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const storeIdempotencyKey = `-- name: StoreIdempotencyKey :one

INSERT INTO idempotency_keys (request_id, operation_type, response_data, expires_at, created_at)
VALUES (?1, ?2, ?3, ?4, CURRENT_TIMESTAMP)
ON CONFLICT(request_id) DO UPDATE SET
    response_data = excluded.response_data,
    expires_at = excluded.expires_at
RETURNING request_id, operation_type, response_data, created_at, expires_at
`

type StoreIdempotencyKeyParams struct {
	RequestID     string         `json:"request_id"`
	OperationType string         `json:"operation_type"`
	ResponseData  sql.NullString `json:"response_data"`
	ExpiresAt     time.Time      `json:"expires_at"`
}

// =====================================================
// IDEMPOTENCY QUERIES
// =====================================================
// Store idempotency key with response
func (q *Queries) StoreIdempotencyKey(ctx context.Context, arg StoreIdempotencyKeyParams) (IdempotencyKey, error) {
	row := q.db.QueryRowContext(ctx, storeIdempotencyKey,
		arg.RequestID,
		arg.OperationType,
		arg.ResponseData,
		arg.ExpiresAt,
	)
	var i IdempotencyKey
	err := row.Scan(
		&i.RequestID,
		&i.OperationType,
		&i.ResponseData,
		&i.CreatedAt,
		&i.ExpiresAt,
	)
	return i, err
}

const updateAvailableStockWithVersion = `-- name: UpdateAvailableStockWithVersion :one
UPDATE inventory_items 
SET 
    available_stock = ?,
    version = version + 1,
    updated_at = CURRENT_TIMESTAMP
WHERE 
    product_id = ? 
    AND version = ?
RETURNING id, product_id, available_stock, reserved_stock, version, created_at, updated_at
`

type UpdateAvailableStockWithVersionParams struct {
	AvailableStock int64  `json:"available_stock"`
	ProductID      string `json:"product_id"`
	Version        int64  `json:"version"`
}

// Optimistic locking: Update available stock with version check
func (q *Queries) UpdateAvailableStockWithVersion(ctx context.Context, arg UpdateAvailableStockWithVersionParams) (InventoryItem, error) {
	row := q.db.QueryRowContext(ctx, updateAvailableStockWithVersion, arg.AvailableStock, arg.ProductID, arg.Version)
	var i InventoryItem
	err := row.Scan(
		&i.ID,
		&i.ProductID,
		&i.AvailableStock,
		&i.ReservedStock,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateReservationStatusById = `-- name: UpdateReservationStatusById :one
UPDATE reservations
SET 
    status = ?,
    updated_at = CURRENT_TIMESTAMP
WHERE id = ?
RETURNING id, request_id, product_id, quantity, status, created_at, updated_at, expires_at
`

type UpdateReservationStatusByIdParams struct {
	Status string `json:"status"`
	ID     string `json:"id"`
}

func (q *Queries) UpdateReservationStatusById(ctx context.Context, arg UpdateReservationStatusByIdParams) (Reservation, error) {
	row := q.db.QueryRowContext(ctx, updateReservationStatusById, arg.Status, arg.ID)
	var i Reservation
	err := row.Scan(
		&i.ID,
		&i.RequestID,
		&i.ProductID,
		&i.Quantity,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ExpiresAt,
	)
	return i, err
}

const updateStockOptimistic = `-- name: UpdateStockOptimistic :one
UPDATE inventory_items 
SET 
    available_stock = ?1 - reserved_stock,  -- New available = total - reserved
    version = version + 1,
    updated_at = CURRENT_TIMESTAMP
WHERE 
    product_id = ?2 
    AND version = ?3
    AND ?1 >= reserved_stock  -- Ensure new total >= reserved
RETURNING id, product_id, available_stock, reserved_stock, version, created_at, updated_at
`

type UpdateStockOptimisticParams struct {
	ReservedStock int64  `json:"reserved_stock"`
	ProductID     string `json:"product_id"`
	Version       int64  `json:"version"`
}

// Critical: Update total stock with version check
func (q *Queries) UpdateStockOptimistic(ctx context.Context, arg UpdateStockOptimisticParams) (InventoryItem, error) {
	row := q.db.QueryRowContext(ctx, updateStockOptimistic, arg.ReservedStock, arg.ProductID, arg.Version)
	var i InventoryItem
	err := row.Scan(
		&i.ID,
		&i.ProductID,
		&i.AvailableStock,
		&i.ReservedStock,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
