// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package repository

import (
	"database/sql"
	"time"
)

type IdempotencyKey struct {
	RequestID     string         `json:"request_id"`
	OperationType string         `json:"operation_type"`
	ResponseData  sql.NullString `json:"response_data"`
	CreatedAt     time.Time      `json:"created_at"`
	ExpiresAt     time.Time      `json:"expires_at"`
}

type InventoryItem struct {
	ID             string    `json:"id"`
	ProductID      string    `json:"product_id"`
	AvailableStock int64     `json:"available_stock"`
	ReservedStock  int64     `json:"reserved_stock"`
	Version        int64     `json:"version"`
	CreatedAt      time.Time `json:"created_at"`
	UpdatedAt      time.Time `json:"updated_at"`
}

type Product struct {
	ID          string         `json:"id"`
	Name        string         `json:"name"`
	Description sql.NullString `json:"description"`
	CreatedAt   time.Time      `json:"created_at"`
	UpdatedAt   time.Time      `json:"updated_at"`
}

type Reservation struct {
	ID        string       `json:"id"`
	RequestID string       `json:"request_id"`
	ProductID string       `json:"product_id"`
	Quantity  int64        `json:"quantity"`
	Status    string       `json:"status"`
	CreatedAt time.Time    `json:"created_at"`
	UpdatedAt time.Time    `json:"updated_at"`
	ExpiresAt sql.NullTime `json:"expires_at"`
}
