// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package repository

import (
	"context"
)

type Querier interface {
	// Cleanup expired idempotency keys
	CleanupExpiredIdempotencyKeys(ctx context.Context) error
	// Convert reservation to sale (decrease reserved, don't change available)
	ConvertReservationToSale(ctx context.Context, arg ConvertReservationToSaleParams) (InventoryItem, error)
	// Idempotency queries (adapting to existing schema)
	CreateIdempotencyKey(ctx context.Context, arg CreateIdempotencyKeyParams) (IdempotencyKey, error)
	// Inventory Items queries (adapting to existing schema)
	CreateInventoryItem(ctx context.Context, arg CreateInventoryItemParams) (InventoryItem, error)
	// Products queries
	CreateProduct(ctx context.Context, arg CreateProductParams) (Product, error)
	// Reservations queries (adapting to existing schema)
	CreateReservation(ctx context.Context, arg CreateReservationParams) (Reservation, error)
	// Create reservation with timeout and validation
	CreateReservationWithTimeout(ctx context.Context, arg CreateReservationWithTimeoutParams) (Reservation, error)
	DeleteExpiredIdempotencyKeys(ctx context.Context) error
	// Update reservation status with optimistic approach\n-- name: UpdateReservationStatus :one\nUPDATE reservations\nSET \n    status = ?1,\n    updated_at = CURRENT_TIMESTAMP\nWHERE id = ?2 AND status = 'active'  -- Only update active reservations\nRETURNING *;
	// Get active reservations for cleanup
	GetExpiredReservations(ctx context.Context, limit int64) ([]GetExpiredReservationsRow, error)
	GetIdempotencyKey(ctx context.Context, requestID string) (IdempotencyKey, error)
	// Get inventory with version for optimistic locking
	GetInventoryForUpdate(ctx context.Context, productID string) (InventoryItem, error)
	GetInventoryItem(ctx context.Context, productID string) (InventoryItem, error)
	GetInventoryItemWithVersion(ctx context.Context, arg GetInventoryItemWithVersionParams) (InventoryItem, error)
	// Inventory reporting queries (adapting to existing schema)
	GetInventorySummary(ctx context.Context) (GetInventorySummaryRow, error)
	GetLowStockProducts(ctx context.Context, availableStock int64) ([]GetLowStockProductsRow, error)
	GetProduct(ctx context.Context, id string) (Product, error)
	GetReservation(ctx context.Context, id string) (Reservation, error)
	GetReservationByRequestID(ctx context.Context, requestID string) (Reservation, error)
	GetReservationsByProduct(ctx context.Context, productID string) ([]Reservation, error)
	// Get idempotency key if not expired
	GetValidIdempotencyKey(ctx context.Context, requestID string) (IdempotencyKey, error)
	ListActiveReservations(ctx context.Context) ([]Reservation, error)
	ListExpiredReservations(ctx context.Context) ([]Reservation, error)
	ListProducts(ctx context.Context) ([]Product, error)
	// Batch release expired reservations
	MarkReservationsExpired(ctx context.Context) error
	// Release reserved stock (decrease reserved, increase available)
	ReleaseReservedStock(ctx context.Context, arg ReleaseReservedStockParams) (InventoryItem, error)
	// Critical: Optimistic stock release with validation
	ReleaseStockOptimistic(ctx context.Context, arg ReleaseStockOptimisticParams) (InventoryItem, error)
	// =====================================================
	// ENHANCED OPTIMISTIC LOCKING QUERIES
	// =====================================================
	// Critical: Optimistic stock reservation with comprehensive validation
	ReserveStockOptimistic(ctx context.Context, arg ReserveStockOptimisticParams) (InventoryItem, error)
	// Reserve stock (decrease available, increase reserved)
	ReserveStockWithVersion(ctx context.Context, arg ReserveStockWithVersionParams) (InventoryItem, error)
	// =====================================================
	// IDEMPOTENCY QUERIES
	// =====================================================
	// Store idempotency key with response
	StoreIdempotencyKey(ctx context.Context, arg StoreIdempotencyKeyParams) (IdempotencyKey, error)
	// Optimistic locking: Update available stock with version check
	UpdateAvailableStockWithVersion(ctx context.Context, arg UpdateAvailableStockWithVersionParams) (InventoryItem, error)
	UpdateReservationStatusById(ctx context.Context, arg UpdateReservationStatusByIdParams) (Reservation, error)
	// Critical: Update total stock with version check
	UpdateStockOptimistic(ctx context.Context, arg UpdateStockOptimisticParams) (InventoryItem, error)
}

var _ Querier = (*Queries)(nil)
